pub const CLASS_SCENE: &[&str] = &[
    "Node", "Node2D", "Node3D", "Resource",
    "CharacterBody2D", "RigidBody2D", "StaticBody2D", "AnimatableBody2D", "Area2D",
    "CollisionShape2D", "RayCast2D", "ShapeCast2D",
    "CharacterBody3D", "RigidBody3D", "StaticBody3D", "AnimatableBody3D", "Area3D",
    "CollisionShape3D", "RayCast3D", "ShapeCast3D",
    "Sprite2D", "AnimatedSprite2D", "Sprite3D", "AnimatedSprite3D",
    "MeshInstance2D", "MeshInstance3D", "MultiMeshInstance2D", "MultiMeshInstance3D",
    "GPUParticles2D", "GPUParticles3D", "CPUParticles2D", "CPUParticles3D",
    "Camera2D", "Camera3D",
    "AnimationPlayer", "AnimationTree", "Tween", "Timer",
    "AudioStreamPlayer", "AudioStreamPlayer2D", "AudioStreamPlayer3D",
    "TileMapLayer", "TileSet",
    "Path2D", "Path3D", "PathFollow2D", "PathFollow3D",
    "Control", "CanvasLayer", "HBoxContainer", "VBoxContainer", "GridContainer",
    "MarginContainer", "CenterContainer", "Label", "Button", "TextureRect",
    "Panel", "ColorRect", "ProgressBar",
    "NavigationAgent2D", "NavigationAgent3D", "NavigationRegion2D", "NavigationRegion3D",
    "PointLight2D", "DirectionalLight2D", "OmniLight3D", "SpotLight3D", "DirectionalLight3D",
    "RectangleShape2D", "CircleShape2D", "CapsuleShape2D", "ConvexPolygonShape2D",
    "BoxShape3D", "SphereShape3D", "CapsuleShape3D", "ConvexPolygonShape3D",
    "BoxMesh", "SphereMesh", "CylinderMesh", "CapsuleMesh", "PlaneMesh", "QuadMesh",
    "PrismMesh", "TorusMesh",
    "StandardMaterial3D", "CanvasItemMaterial", "ShaderMaterial",
    "Vector2", "Vector3", "Color", "Transform2D", "Transform3D", "Basis", "Rect2",
    "PackedScene",
];

pub const CLASS_SCRIPT: &[&str] = &[
    "Node", "Node2D", "Node3D", "Object", "RefCounted", "Resource",
    "CharacterBody2D", "RigidBody2D", "StaticBody2D", "AnimatableBody2D", "Area2D",
    "CollisionShape2D", "CollisionPolygon2D", "RayCast2D", "ShapeCast2D",
    "CharacterBody3D", "RigidBody3D", "StaticBody3D", "AnimatableBody3D", "Area3D",
    "CollisionShape3D", "CollisionPolygon3D", "RayCast3D", "ShapeCast3D",
    "Sprite2D", "AnimatedSprite2D", "Sprite3D", "AnimatedSprite3D",
    "MeshInstance2D", "MeshInstance3D", "MultiMeshInstance2D", "MultiMeshInstance3D",
    "GPUParticles2D", "GPUParticles3D", "CPUParticles2D", "CPUParticles3D",
    "Camera2D", "Camera3D",
    "AnimationPlayer", "AnimationTree", "AnimationMixer", "Tween", "Timer",
    "AudioStreamPlayer", "AudioStreamPlayer2D", "AudioStreamPlayer3D",
    "TileMapLayer", "TileSet",
    "Path2D", "Path3D", "PathFollow2D", "PathFollow3D",
    "Control", "Container", "CanvasLayer", "CanvasItem",
    "HBoxContainer", "VBoxContainer", "GridContainer", "MarginContainer", "CenterContainer",
    "PanelContainer", "ScrollContainer", "AspectRatioContainer",
    "Label", "RichTextLabel", "Button", "TextureButton", "LineEdit", "TextEdit",
    "SpinBox", "Slider", "HSlider", "VSlider", "ProgressBar",
    "CheckBox", "CheckButton", "OptionButton", "ItemList", "Tree",
    "Panel", "TextureRect", "ColorRect",
    "Input", "InputEvent", "InputEventKey", "InputEventMouseButton",
    "InputEventMouseMotion", "InputEventAction",
    "PackedScene", "Texture2D", "ImageTexture", "AtlasTexture",
    "AudioStream", "AudioStreamWAV", "AudioStreamMP3", "AudioStreamOggVorbis",
    "Font", "FontFile", "Theme", "StyleBox",
    "Mesh", "ArrayMesh", "PrimitiveMesh", "BoxMesh", "SphereMesh", "CylinderMesh",
    "Material", "StandardMaterial3D", "ShaderMaterial", "CanvasItemMaterial",
    "Shape2D", "RectangleShape2D", "CircleShape2D", "CapsuleShape2D", "ConvexPolygonShape2D",
    "Shape3D", "BoxShape3D", "SphereShape3D", "CapsuleShape3D", "ConvexPolygonShape3D",
    "NavigationAgent2D", "NavigationAgent3D", "NavigationRegion2D", "NavigationRegion3D",
    "Light2D", "PointLight2D", "DirectionalLight2D",
    "Light3D", "OmniLight3D", "SpotLight3D", "DirectionalLight3D",
    "Vector2", "Vector3", "Vector4", "Rect2", "Transform2D", "Transform3D",
    "Basis", "Quaternion", "AABB", "Plane", "Color",
    "SceneTree", "Engine", "Callable", "Signal",
    "Curve", "Curve2D", "Curve3D", "Gradient",
];

pub const PRIORITY_CLASSES: &[&str] = &[
    "Node", "Node2D", "Node3D", "Object", "RefCounted", "Resource",
    "CharacterBody2D", "RigidBody2D", "StaticBody2D", "AnimatableBody2D", "Area2D",
    "CollisionShape2D", "CollisionPolygon2D", "RayCast2D", "ShapeCast2D",
    "CharacterBody3D", "RigidBody3D", "StaticBody3D", "AnimatableBody3D", "Area3D",
    "CollisionShape3D", "CollisionPolygon3D", "RayCast3D", "ShapeCast3D",
    "Sprite2D", "AnimatedSprite2D", "Sprite3D", "AnimatedSprite3D",
    "MeshInstance2D", "MeshInstance3D", "MultiMeshInstance2D", "MultiMeshInstance3D",
    "GPUParticles2D", "GPUParticles3D", "CPUParticles2D", "CPUParticles3D",
    "Camera2D", "Camera3D",
    "AnimationPlayer", "AnimationTree", "AnimationMixer", "Tween", "Timer",
    "AudioStreamPlayer", "AudioStreamPlayer2D", "AudioStreamPlayer3D",
    "TileMap", "TileMapLayer", "TileSet",
    "Path2D", "Path3D", "PathFollow2D", "PathFollow3D",
    "Control", "Container", "CanvasLayer", "CanvasItem",
    "HBoxContainer", "VBoxContainer", "GridContainer", "MarginContainer", "CenterContainer",
    "PanelContainer", "ScrollContainer", "AspectRatioContainer",
    "Label", "RichTextLabel", "Button", "TextureButton", "LineEdit", "TextEdit",
    "SpinBox", "Slider", "HSlider", "VSlider", "ProgressBar",
    "CheckBox", "CheckButton", "OptionButton", "ItemList", "Tree",
    "Panel", "TextureRect", "ColorRect",
    "InputEvent", "InputEventKey", "InputEventMouseButton",
    "InputEventMouseMotion", "InputEventAction",
    "PackedScene", "Texture2D", "ImageTexture", "AtlasTexture",
    "AudioStream", "AudioStreamWAV", "AudioStreamMP3", "AudioStreamOggVorbis",
    "Font", "FontFile", "Theme", "StyleBox",
    "Mesh", "ArrayMesh", "PrimitiveMesh", "BoxMesh", "SphereMesh", "CylinderMesh",
    "Material", "StandardMaterial3D", "ShaderMaterial", "CanvasItemMaterial",
    "Shape2D", "RectangleShape2D", "CircleShape2D", "CapsuleShape2D", "ConvexPolygonShape2D",
    "Shape3D", "BoxShape3D", "SphereShape3D", "CapsuleShape3D", "ConvexPolygonShape3D",
    "NavigationAgent2D", "NavigationAgent3D", "NavigationRegion2D", "NavigationRegion3D",
    "Light2D", "PointLight2D", "DirectionalLight2D",
    "Light3D", "OmniLight3D", "SpotLight3D", "DirectionalLight3D",
    "Vector2", "Vector3", "Vector4", "Rect2", "Transform2D", "Transform3D",
    "Basis", "Quaternion", "AABB", "Plane", "Color",
];

pub const CLASS_UNIFIED: &[&str] = &[
    "Node", "Node2D", "Node3D", "Object", "RefCounted", "Resource",
    "CharacterBody2D", "RigidBody2D", "StaticBody2D", "AnimatableBody2D", "Area2D",
    "CollisionShape2D", "CollisionPolygon2D", "RayCast2D", "ShapeCast2D",
    "CharacterBody3D", "RigidBody3D", "StaticBody3D", "AnimatableBody3D", "Area3D",
    "CollisionShape3D", "CollisionPolygon3D", "RayCast3D", "ShapeCast3D",
    "Sprite2D", "AnimatedSprite2D", "Sprite3D", "AnimatedSprite3D",
    "MeshInstance2D", "MeshInstance3D", "MultiMeshInstance2D", "MultiMeshInstance3D",
    "GPUParticles2D", "GPUParticles3D", "CPUParticles2D", "CPUParticles3D",
    "Camera2D", "Camera3D",
    "AnimationPlayer", "AnimationTree", "Tween", "Timer",
    "AudioStreamPlayer", "AudioStreamPlayer2D", "AudioStreamPlayer3D",
    "TileMapLayer", "TileSet",
    "Path2D", "Path3D", "PathFollow2D", "PathFollow3D", "Curve2D", "Curve3D",
    "Control", "Container", "CanvasLayer", "CanvasItem",
    "HBoxContainer", "VBoxContainer", "GridContainer", "MarginContainer", "CenterContainer",
    "PanelContainer", "ScrollContainer",
    "Label", "Button", "TextureButton", "LineEdit", "ProgressBar",
    "Slider", "HSlider", "VSlider", "CheckBox",
    "Panel", "TextureRect", "ColorRect",
    "Input", "InputEvent",
    "PackedScene", "Texture2D", "AudioStream", "Mesh", "Material",
    "StandardMaterial3D", "ShaderMaterial", "CanvasItemMaterial",
    "Shape2D", "RectangleShape2D", "CircleShape2D", "CapsuleShape2D", "ConvexPolygonShape2D",
    "Shape3D", "BoxShape3D", "SphereShape3D", "CapsuleShape3D", "ConvexPolygonShape3D",
    "PrimitiveMesh", "BoxMesh", "SphereMesh", "CylinderMesh", "CapsuleMesh", "PlaneMesh",
    "NavigationAgent2D", "NavigationAgent3D", "NavigationRegion2D", "NavigationRegion3D",
    "Light2D", "PointLight2D", "DirectionalLight2D",
    "Light3D", "OmniLight3D", "SpotLight3D", "DirectionalLight3D",
    "Vector2", "Vector3", "Vector4", "Rect2", "Transform2D", "Transform3D",
    "Basis", "Quaternion", "AABB", "Plane", "Color",
    "SceneTree", "Engine", "Callable", "Signal",
];
